# Generated by Django 5.0.14 on 2025-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('CAN', 'Canada'), ('MEX', 'Mexico')], default='USA', max_length=3),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='product_pro_created_22b186_idx'),
        ),
    ]
